refactor all peer code to query syntax
all peer methods cleanedup and refactored so no peer methods are used any
exception: addSearchToCriteria, needs to be moved to Query::filterBySearch() with a update to Propel2

fix sender_emails config default